export const guides = [
  {
    slug: "saas-gross-margin-targets",
    title: "SaaS Gross Margin Targets (How to Choose a Range)",
    description: "A practical way to pick a gross margin target and avoid common modeling mistakes.",
    tags: ["gross-margin", "unit-economics"],
    tools: [
      "usage-based-pricing-calculator",
      "compute-cost-estimator",
      "bandwidth-cost-calculator",
      "storage-cost-calculator",
      "monthly-cloud-cost-estimator",
      "api-pricing-calculator",
    ],
    glossary: ["gross-margin", "cogs", "unit-economics"],
  },
  {
    slug: "seat-vs-usage-pricing",
    title: "Seat vs Usage Pricing (Decision Framework)",
    description: "A decision framework for choosing seat-based or usage-based pricing, including minimums, tiers, and guardrails.",
    tags: ["pricing-models"],
    tools: ["seat-vs-usage-pricing-comparison", "usage-based-pricing-calculator", "tiered-usage-pricing-calculator"],
    glossary: ["seat-based-pricing", "usage-based-pricing"],
  },
  {
    slug: "pricing-experiments-playbook",
    title: "Pricing Experiments Playbook",
    description: "How to run price increases and annual prepay tests with clear metrics and guardrails.",
    tags: ["pricing-experiments"],
    tools: ["pricing-increase-impact-calculator", "annual-discount-calculator", "churn-impact-calculator", "mrr-calculator"],
    glossary: ["churn", "mrr", "annual-prepay-discount"],
  },
  {
    slug: "usage-based-pricing-examples",
    title: "Usage-Based Pricing Examples (Units, Tiers, Minimums)",
    description: "Concrete examples you can adapt to calls, events, GB, minutes, and messages.",
    tags: ["usage-based-pricing"],
    tools: ["usage-based-pricing-calculator", "tiered-usage-pricing-calculator", "api-pricing-calculator", "storage-cost-calculator"],
    glossary: ["usage-based-pricing", "gross-margin"],
  },
  {
    slug: "api-pricing-model",
    title: "API Pricing Model (How to Price per 1k Calls)",
    description: "A step-by-step model for costs, margins, and tier design for API products.",
    tags: ["api-pricing"],
    tools: ["api-pricing-calculator", "api-cost-estimator", "tiered-usage-pricing-calculator"],
    glossary: ["usage-based-pricing", "gross-margin", "cogs"],
  },
  {
    slug: "api-cost-estimation",
    title: "API Cost Estimation (Cost per Call)",
    description: "How to estimate cost per request, include vendor costs, and avoid margin surprises.",
    tags: ["api-costs"],
    tools: ["api-cost-estimator", "compute-cost-estimator", "monthly-cloud-cost-estimator"],
    glossary: ["cogs", "gross-margin"],
  },
  {
    slug: "annual-prepay-discount",
    title: "Annual Prepay Discount (Break-Even Guide)",
    description: "How to choose an annual discount with churn and cash-flow in mind.",
    tags: ["annual-pricing"],
    tools: ["annual-discount-calculator", "pricing-increase-impact-calculator", "churn-impact-calculator"],
    glossary: ["annual-prepay-discount", "churn", "mrr"],
  },
  {
    slug: "storage-costs-and-pricing",
    title: "Storage Costs & Pricing (Cost per GB-Month)",
    description: "How to model storage costs, request costs, and a margin-safe price.",
    tags: ["storage", "unit-costs"],
    tools: ["storage-cost-calculator", "price-per-gb-month-calculator", "bandwidth-cost-calculator"],
    glossary: ["cogs", "gross-margin"],
  },
  {
    slug: "tiered-usage-pricing",
    title: "Tiered Usage Pricing (Tiers, Overages, Minimums)",
    description: "How to design tiers that reduce bill shock while protecting margins at p90 usage.",
    tags: ["tiers"],
    tools: ["tiered-usage-pricing-calculator", "usage-based-pricing-calculator"],
    glossary: ["usage-based-pricing"],
  },
  {
    slug: "saas-metrics-cheat-sheet",
    title: "SaaS Metrics Cheat Sheet (MRR, ARR, LTV, CAC)",
    description: "Definitions, formulas, and what to watch when you model pricing changes.",
    tags: ["saas-metrics"],
    tools: ["mrr-calculator", "arr-calculator", "ltv-calculator", "cac-payback-period-calculator", "break-even-cac-calculator"],
    glossary: ["mrr", "arr", "ltv", "cac", "cac-payback", "churn"],
  },
  // New guides to expand long-tail coverage (keep these practical and calculator-linked).
  {
    slug: "price-per-gb-month-explained",
    title: "Price per GB-Month (What It Means + Examples)",
    description: "How GB-month pricing works, how to explain it on a pricing page, and example workloads.",
    tags: ["storage"],
    tools: ["price-per-gb-month-calculator", "storage-cost-calculator"],
    glossary: ["gb-month", "storage-costs", "cogs"],
  },
  {
    slug: "api-tier-design",
    title: "API Tier Design (Breakpoints, Overages, Included Calls)",
    description: "How to pick tier breakpoints and included usage so bills stay predictable while margins hold.",
    tags: ["api-pricing", "tiers"],
    tools: ["tiered-usage-pricing-calculator", "api-pricing-calculator", "api-cost-estimator"],
    glossary: ["usage-based-pricing", "gross-margin"],
  },
  {
    slug: "free-tier-modeling",
    title: "Free Tier Modeling (When It Works, When It Burns You)",
    description: "How to model free tiers, included usage, and abuse risk using simple cost and margin checks.",
    tags: ["free-tier"],
    tools: ["api-cost-estimator", "usage-based-pricing-calculator"],
    glossary: ["cogs", "gross-margin", "included-usage"],
  },
  {
    slug: "usage-based-pricing-bill-shock",
    title: "Avoiding Bill Shock in Usage-Based Pricing",
    description: "Guardrails that reduce churn and support load: minimums, tiers, caps, alerts, and examples.",
    tags: ["usage-based-pricing"],
    tools: ["tiered-usage-pricing-calculator", "usage-based-pricing-calculator"],
    glossary: ["usage-based-pricing", "churn"],
  },
  {
    slug: "pricing-page-unit-definition",
    title: "Pricing Page Unit Definitions (Make Units Buyer-Friendly)",
    description: "How to define units like 'requests', 'events', and 'GB-month' so buyers can estimate costs confidently.",
    tags: ["pricing-page"],
    tools: ["usage-based-pricing-calculator", "price-per-gb-month-calculator", "api-cost-estimator"],
    glossary: ["usage-based-pricing", "gb-month"],
  },
  {
    slug: "gross-margin-vs-contribution-margin",
    title: "Gross Margin vs Contribution Margin (Which to Use for Pricing)",
    description: "When to use gross margin vs contribution margin in pricing and CAC payback models.",
    tags: ["unit-economics"],
    tools: ["break-even-cac-calculator", "ltv-calculator"],
    glossary: ["gross-margin", "contribution-margin", "cogs", "cac"],
  },
  {
    slug: "ltv-cac-benchmarks",
    title: "LTV:CAC Benchmarks (How to Interpret the Ratio)",
    description: "How to interpret LTV:CAC, why it breaks, and what to adjust in your assumptions.",
    tags: ["saas-metrics"],
    tools: ["ltv-calculator", "break-even-cac-calculator", "cac-payback-period-calculator"],
    glossary: ["ltv", "cac", "cac-payback", "churn"],
  },
  {
    slug: "cac-payback-targets",
    title: "CAC Payback Targets (How Many Months Is Healthy?)",
    description: "How to think about CAC payback targets by channel and growth stage, with trade-offs.",
    tags: ["saas-metrics"],
    tools: ["cac-payback-period-calculator", "break-even-cac-calculator"],
    glossary: ["cac", "cac-payback", "gross-margin"],
  },
  {
    slug: "annual-discount-mistakes",
    title: "Annual Discount Mistakes (How Teams Over-Discount)",
    description: "Common mistakes with annual discounts and how to sanity-check them with effective rate and churn thinking.",
    tags: ["annual-pricing"],
    tools: ["annual-discount-calculator", "churn-impact-calculator"],
    glossary: ["annual-prepay-discount", "churn", "mrr"],
  },
  {
    slug: "storage-request-costs",
    title: "Storage Request Costs (When Requests Matter)",
    description: "When request pricing is material, how to model it, and how to reflect it in pricing.",
    tags: ["storage"],
    tools: ["storage-cost-calculator"],
    glossary: ["request-pricing", "cogs"],
  },
  {
    slug: "bandwidth-pricing-guide",
    title: "Bandwidth Pricing Guide (Egress Cost Recovery)",
    description: "How to price bandwidth/egress features using blended costs, tiers, and gross margin targets.",
    tags: ["bandwidth"],
    tools: ["bandwidth-cost-calculator", "usage-based-pricing-calculator"],
    glossary: ["egress", "gross-margin", "cogs"],
  },
  {
    slug: "unit-economics-model-template",
    title: "Unit Economics Model Template (What to Include)",
    description: "A checklist for building a lightweight unit economics model you can keep accurate as costs change.",
    tags: ["unit-economics"],
    tools: ["ltv-calculator", "cac-payback-period-calculator", "break-even-cac-calculator"],
    glossary: ["unit-economics", "gross-margin", "cogs", "cac", "ltv"],
  },
  {
    slug: "mrr-to-arr-and-back",
    title: "MRR to ARR (And Back): How to Avoid Confusion",
    description: "How to use MRR/ARR correctly when you have annual plans, usage overages, and discounts.",
    tags: ["saas-metrics"],
    tools: ["mrr-calculator", "arr-calculator", "annual-discount-calculator"],
    glossary: ["mrr", "arr", "annual-prepay-discount"],
  },
  {
    slug: "pricing-increase-playbook",
    title: "Price Increase Playbook (Break-Even + Communication)",
    description: "How to model a price increase, estimate break-even churn, and roll it out safely.",
    tags: ["pricing-experiments"],
    tools: ["pricing-increase-impact-calculator", "churn-impact-calculator"],
    glossary: ["churn", "mrr"],
  },
];

export const glossary = [
  // Core SaaS + pricing terms (includes the ones we previously had as .astro pages).
  { slug: "mrr", title: "MRR (Monthly Recurring Revenue)", description: "Recurring revenue run-rate per month and how to compute it.", category: "metrics", tools: ["mrr-calculator", "arr-calculator"], glossary: ["arr", "churn"] },
  { slug: "arr", title: "ARR (Annual Recurring Revenue)", description: "Annualized recurring revenue (often MRR × 12) and when it’s useful.", category: "metrics", tools: ["arr-calculator", "mrr-calculator"], glossary: ["mrr"] },
  { slug: "gross-margin", title: "Gross Margin", description: "The percent of revenue left after COGS; a core constraint for pricing.", category: "unit-economics", tools: ["usage-based-pricing-calculator", "api-pricing-calculator"], glossary: ["cogs"] },
  { slug: "cogs", title: "COGS (Cost of Goods Sold)", description: "Direct costs to deliver your product (infra + vendor costs for SaaS).", category: "unit-economics", tools: ["compute-cost-estimator", "storage-cost-calculator"], glossary: ["gross-margin"] },
  { slug: "churn", title: "Churn (Customer & Revenue)", description: "Loss of customers or recurring revenue over time (logo vs revenue churn).", category: "metrics", tools: ["churn-impact-calculator", "ltv-calculator"], glossary: ["mrr", "ltv"] },
  { slug: "arpa", title: "ARPA / ARPU", description: "Average revenue per account (or user) used in LTV and payback models.", category: "metrics", tools: ["ltv-calculator", "cac-payback-period-calculator"], glossary: ["ltv"] },
  { slug: "ltv", title: "LTV (Customer Lifetime Value)", description: "Expected gross profit over a customer’s lifetime and key assumptions.", category: "unit-economics", tools: ["ltv-calculator", "break-even-cac-calculator"], glossary: ["arpa", "churn"] },
  { slug: "cac", title: "CAC (Customer Acquisition Cost)", description: "Cost to acquire a customer; use with gross profit to estimate payback.", category: "unit-economics", tools: ["cac-payback-period-calculator", "break-even-cac-calculator"], glossary: ["cac-payback", "ltv"] },
  { slug: "cac-payback", title: "CAC Payback Period", description: "How many months of gross profit it takes to recover CAC.", category: "unit-economics", tools: ["cac-payback-period-calculator"], glossary: ["cac", "gross-margin"] },
  { slug: "unit-economics", title: "Unit Economics", description: "Per-customer (or per-unit) profitability: margins, payback, and LTV.", category: "unit-economics", tools: ["ltv-calculator", "break-even-cac-calculator"], glossary: ["gross-margin", "cac", "ltv"] },
  { slug: "usage-based-pricing", title: "Usage-Based Pricing", description: "Charging based on consumption (calls, events, GB, minutes) instead of seats alone.", category: "pricing-models", tools: ["usage-based-pricing-calculator", "tiered-usage-pricing-calculator"], glossary: ["seat-based-pricing"] },
  { slug: "seat-based-pricing", title: "Seat-Based Pricing", description: "Charging by number of users; simple but can break when costs scale with usage.", category: "pricing-models", tools: ["seat-vs-usage-pricing-comparison"], glossary: ["usage-based-pricing"] },
  { slug: "annual-prepay-discount", title: "Annual Prepay Discount", description: "Discount for annual commitment; trades revenue for cash flow and retention.", category: "pricing-experiments", tools: ["annual-discount-calculator"], glossary: ["mrr", "churn"] },
  // Expansion set (pricing, usage, API, storage, experiments, analytics).
  { slug: "nrr", title: "NRR (Net Revenue Retention)", description: "Revenue retention including expansions; key for growth and pricing impact.", category: "metrics", glossary: ["grr", "churn"] },
  { slug: "grr", title: "GRR (Gross Revenue Retention)", description: "Revenue retention excluding expansions; isolates churn and downgrades.", category: "metrics", glossary: ["nrr", "churn"] },
  { slug: "arpa-per-seat", title: "Revenue per Seat", description: "Average recurring revenue per seat and how it changes under pricing models.", category: "metrics", glossary: ["arpa", "seat-based-pricing"] },
  { slug: "expansion-revenue", title: "Expansion Revenue", description: "Revenue gained from existing customers via upsells, usage growth, or add-ons.", category: "metrics", glossary: ["nrr", "arpa"] },
  { slug: "downgrade", title: "Downgrade", description: "Reduction in recurring revenue from a customer due to lower plan or usage.", category: "metrics", glossary: ["grr", "churn"] },
  { slug: "logo-churn", title: "Logo Churn", description: "Percent of customers who cancel in a period (customer churn).", category: "metrics", glossary: ["churn"] },
  { slug: "revenue-churn", title: "Revenue Churn", description: "Percent of recurring revenue lost in a period (gross or net).", category: "metrics", glossary: ["churn", "mrr"] },
  { slug: "unit-cost", title: "Unit Cost", description: "Cost per unit of usage (call, event, GB, minute) used to set margin-safe prices.", category: "unit-economics", tools: ["usage-based-pricing-calculator", "api-cost-estimator"], glossary: ["cogs", "gross-margin"] },
  { slug: "blended-cost", title: "Blended Cost", description: "Weighted average unit cost across regions, tiers, and discounts.", category: "unit-economics", glossary: ["unit-cost"] },
  { slug: "contribution-margin", title: "Contribution Margin", description: "Margin after variable costs (often gross profit minus variable S&M/support).", category: "unit-economics", glossary: ["gross-margin", "cac"] },
  { slug: "payback-period", title: "Payback Period", description: "Time required to recover an investment, often CAC payback in SaaS.", category: "unit-economics", tools: ["cac-payback-period-calculator"], glossary: ["cac-payback", "cac"] },
  { slug: "ltv-cac", title: "LTV:CAC", description: "Ratio of lifetime gross profit to CAC; a common unit economics health check.", category: "unit-economics", glossary: ["ltv", "cac"] },
  { slug: "arpu", title: "ARPU", description: "Average revenue per user; used more in consumer apps than B2B accounts.", category: "metrics", glossary: ["arpa"] },
  { slug: "arrr", title: "ARRR Funnel", description: "Acquisition, Activation, Retention, Revenue, Referral; a growth framework.", category: "metrics" },
  { slug: "activation", title: "Activation", description: "The moment a user experiences core value; affects conversion and payback.", category: "metrics" },
  { slug: "time-to-value", title: "Time to Value", description: "How quickly a customer reaches value; impacts churn and pricing tolerance.", category: "metrics" },
  { slug: "churn-mitigation", title: "Churn Mitigation", description: "Tactics to reduce churn (onboarding, alerts, guardrails, packaging).", category: "metrics", glossary: ["churn"] },
  // Usage pricing mechanics.
  { slug: "included-usage", title: "Included Usage", description: "Usage bundled into a plan or platform fee before overages apply.", category: "pricing-models", glossary: ["usage-based-pricing"] },
  { slug: "overage", title: "Overage", description: "Charges applied when a customer exceeds included usage or plan limits.", category: "pricing-models", tools: ["tiered-usage-pricing-calculator"], glossary: ["included-usage"] },
  { slug: "tiers", title: "Pricing Tiers", description: "Multiple pricing levels or volume bands used to simplify and reduce bill shock.", category: "pricing-models", tools: ["tiered-usage-pricing-calculator"], glossary: ["overage"] },
  { slug: "minimum-commitment", title: "Minimum Commitment", description: "A minimum monthly or annual spend requirement, often paired with usage pricing.", category: "pricing-models", glossary: ["usage-based-pricing"] },
  { slug: "platform-fee", title: "Platform Fee", description: "Base recurring fee that covers baseline value and overhead before usage charges.", category: "pricing-models", tools: ["tiered-usage-pricing-calculator"], glossary: ["included-usage"] },
  { slug: "bill-shock", title: "Bill Shock", description: "Unexpectedly high invoices in usage pricing; reduces retention and trust.", category: "pricing-models", glossary: ["usage-based-pricing", "churn"] },
  { slug: "value-metric", title: "Value Metric", description: "The metric that best correlates with value delivered (seat, call, GB, etc.).", category: "pricing-models", glossary: ["usage-based-pricing", "seat-based-pricing"] },
  { slug: "pricing-metric", title: "Pricing Metric", description: "The unit you charge on; should be buyer-friendly and align with value/cost.", category: "pricing-models", glossary: ["value-metric"] },
  // API / infra terms.
  { slug: "api-call", title: "API Call", description: "A request to an API endpoint; can be priced per call or per 1,000 calls.", category: "api" },
  { slug: "request", title: "Request", description: "A single operation sent to a service (API request, storage request, etc.).", category: "api" },
  { slug: "request-pricing", title: "Request Pricing", description: "Charging per request (or per 10k/1M requests) when request volume drives cost.", category: "api", tools: ["storage-cost-calculator"] },
  { slug: "rate-limit", title: "Rate Limit", description: "Limits on requests per time window; can protect cost and plan fairness.", category: "api" },
  { slug: "throttling", title: "Throttling", description: "Delaying or rejecting requests when usage exceeds limits; impacts user experience.", category: "api", glossary: ["rate-limit"] },
  { slug: "burst-traffic", title: "Burst Traffic", description: "Spiky usage patterns; increases risk in usage-based pricing and capacity planning.", category: "api" },
  { slug: "p50", title: "P50 (Median) Usage", description: "Typical usage level; useful for designing included usage and starter tiers.", category: "modeling" },
  { slug: "p90", title: "P90 Usage", description: "Heavy usage level; use to protect gross margin and avoid subsidizing power users.", category: "modeling" },
  { slug: "unit-test-scenario", title: "Scenario Modeling", description: "Best/base/worst cases (p50 vs p90) used to stress-test pricing.", category: "modeling", glossary: ["p50", "p90"] },
  // Storage and bandwidth.
  { slug: "gb-month", title: "GB-Month", description: "Storage measured as average GB stored over a month (GB × time).", category: "storage", tools: ["price-per-gb-month-calculator", "storage-cost-calculator"] },
  { slug: "storage-costs", title: "Storage Costs", description: "Costs to store data plus requests, replication, backups, and overhead.", category: "storage", tools: ["storage-cost-calculator"] },
  { slug: "egress", title: "Egress", description: "Outbound data transfer; often a significant variable cost for infra products.", category: "storage", tools: ["bandwidth-cost-calculator"] },
  { slug: "bandwidth", title: "Bandwidth", description: "Data transferred per time; frequently priced per GB with volume tiers.", category: "storage", tools: ["bandwidth-cost-calculator"] },
  { slug: "origin-fetch", title: "Origin Fetch", description: "Traffic from CDN to origin; can affect egress and cost structure.", category: "storage" },
  { slug: "cdn", title: "CDN", description: "Content Delivery Network; reduces origin load but can introduce request fees.", category: "storage" },
  { slug: "replication", title: "Replication", description: "Storing multiple copies for durability/availability; increases GB-month cost.", category: "storage" },
  { slug: "backup", title: "Backups", description: "Data copies for recovery; often adds storage overhead and retrieval costs.", category: "storage" },
  { slug: "retrieval-fees", title: "Retrieval Fees", description: "Fees to read data back from cold storage; important for archival products.", category: "storage" },
  // Pricing experiments and packaging.
  { slug: "grandfathering", title: "Grandfathering", description: "Keeping existing customers on old pricing to reduce churn risk during increases.", category: "pricing-experiments", glossary: ["churn"] },
  { slug: "price-increase", title: "Price Increase", description: "Raising prices; evaluate break-even churn and rollout strategy.", category: "pricing-experiments", tools: ["pricing-increase-impact-calculator"], glossary: ["churn"] },
  { slug: "break-even-churn", title: "Break-Even Churn", description: "Churn rate at which a price increase stops being beneficial.", category: "pricing-experiments", tools: ["pricing-increase-impact-calculator"], glossary: ["churn"] },
  { slug: "discount", title: "Discount", description: "Reducing price to drive conversion or commitment; must be modeled for margin impact.", category: "pricing-experiments", tools: ["annual-discount-calculator"] },
  { slug: "annual-plan", title: "Annual Plan", description: "A plan billed yearly; often includes discounts and changes cash timing.", category: "pricing-experiments", glossary: ["annual-prepay-discount"] },
  { slug: "effective-monthly-rate", title: "Effective Monthly Rate", description: "Annual prepay price spread over 12 months; used to compare monthly vs annual.", category: "pricing-experiments", tools: ["annual-discount-calculator"] },
  { slug: "cohort", title: "Cohort", description: "Group of customers sharing a start date; used to measure churn and retention.", category: "metrics" },
  { slug: "a-b-test", title: "A/B Test", description: "Experiment comparing two variants; used for pricing pages and packaging.", category: "pricing-experiments" },
  { slug: "pricing-page", title: "Pricing Page", description: "Your plan and unit definitions; must be clear to avoid sales/support friction.", category: "pricing-experiments" },
  // Add-ons and packaging.
  { slug: "add-on", title: "Add-on", description: "Optional feature or capacity sold separately; useful for cost recovery.", category: "pricing-models" },
  { slug: "feature-gating", title: "Feature Gating", description: "Restricting features by plan; shifts value capture beyond just usage.", category: "pricing-models" },
  { slug: "packaging", title: "Packaging", description: "How you bundle features and limits into plans; affects ARPA and conversion.", category: "pricing-models" },
  // Operational.
  { slug: "support-costs", title: "Support Costs", description: "Support effort that may scale with accounts or usage; influences COGS decisions.", category: "unit-economics" },
  { slug: "on-call", title: "On-call", description: "Operational coverage for incidents; often part of overhead recovery.", category: "unit-economics" },
  // Additional glossary pages to push toward ~150 total site URLs.
  { slug: "token-pricing", title: "Token Pricing", description: "Pricing based on tokens (common for LLM/AI usage); requires careful unit definitions.", category: "api", glossary: ["unit-cost", "usage-based-pricing"] },
  { slug: "per-active-user", title: "Per Active User", description: "Charging based on active users instead of total seats; aligns price with usage intensity.", category: "pricing-models", glossary: ["seat-based-pricing"] },
  { slug: "per-seat", title: "Per Seat", description: "Charging per user seat; simple to explain but can misalign with cost for automation-heavy customers.", category: "pricing-models", glossary: ["seat-based-pricing"] },
  { slug: "usage-cap", title: "Usage Cap", description: "A maximum usage limit (hard or soft) used to prevent runaway costs and bill shock.", category: "pricing-models", glossary: ["bill-shock", "usage-based-pricing"] },
  { slug: "fair-use", title: "Fair Use Policy", description: "Policy that limits extreme usage on flat-rate plans; reduces abuse risk but must be explicit.", category: "pricing-models", glossary: ["usage-cap"] },
  { slug: "rate-card", title: "Rate Card", description: "A list of unit prices for usage, add-ons, and services; useful for enterprise quoting.", category: "pricing-models" },
  { slug: "billing-cycle", title: "Billing Cycle", description: "How often you invoice (monthly, annual); affects churn measurement and cash flow.", category: "pricing-experiments", glossary: ["mrr", "annual-plan"] },
  { slug: "grace-period", title: "Grace Period", description: "Time window before enforcing limits after payment failure or overage; impacts churn and support.", category: "pricing-experiments" },
  { slug: "run-rate", title: "Run Rate", description: "A normalized revenue pace (e.g., MRR) used to project annualized performance.", category: "metrics", glossary: ["mrr", "arr"] },
  { slug: "net-new-mrr", title: "Net New MRR", description: "MRR change after new, expansion, contraction, and churn; a growth KPI.", category: "metrics", tools: ["mrr-calculator"], glossary: ["mrr", "expansion-revenue", "downgrade", "churn"] },
  { slug: "bookings", title: "Bookings", description: "Contracted revenue (often annual) that may differ from recognized revenue and ARR.", category: "metrics", glossary: ["arr", "annual-plan"] },
  { slug: "revenue-recognition", title: "Revenue Recognition", description: "Accounting treatment of revenue over time; differs from cash collected.", category: "metrics", glossary: ["bookings", "run-rate"] },
  { slug: "contract-value", title: "Contract Value", description: "Value of a contract over its term; commonly expressed as TCV or ACV.", category: "metrics", glossary: ["tcv", "acv"] },
  { slug: "tcv", title: "TCV (Total Contract Value)", description: "Total value over the full contract term (including multi-year commitments).", category: "metrics", glossary: ["contract-value"] },
  { slug: "acv", title: "ACV (Annual Contract Value)", description: "Annualized contract value; often used for sales performance and enterprise pricing.", category: "metrics", glossary: ["contract-value"] },
  { slug: "marginal-cost", title: "Marginal Cost", description: "Incremental cost to serve one more unit or customer; key for usage pricing.", category: "unit-economics", glossary: ["unit-cost", "variable-cost"] },
  { slug: "fixed-cost", title: "Fixed Cost", description: "Cost that does not scale directly with usage (within a range); often recovered via platform fees.", category: "unit-economics", glossary: ["platform-fee"] },
  { slug: "variable-cost", title: "Variable Cost", description: "Cost that scales with usage (calls, GB, minutes); drives unit economics and margin.", category: "unit-economics", glossary: ["unit-cost", "marginal-cost"] },
  { slug: "cohort-retention", title: "Cohort Retention", description: "Retention measured by customer cohorts over time; helps interpret churn correctly.", category: "metrics", glossary: ["cohort", "churn"] },
  { slug: "retention-curve", title: "Retention Curve", description: "Retention plotted over time; highlights early churn vs long-term stickiness.", category: "metrics", glossary: ["cohort-retention"] },
  { slug: "upsell", title: "Upsell", description: "Selling a higher plan or add-on to an existing customer; contributes to expansion revenue.", category: "metrics", glossary: ["expansion-revenue"] },
  { slug: "cross-sell", title: "Cross-sell", description: "Selling a different product or add-on to an existing customer; can improve ARPA.", category: "metrics", glossary: ["arpa", "expansion-revenue"] },
  { slug: "churn-cohort", title: "Churn Cohort", description: "Churn measured by cohort to avoid misleading period-over-period comparisons.", category: "metrics", glossary: ["cohort", "churn"] },
  { slug: "ramp", title: "Ramp", description: "How quickly customers grow into paid usage after signing up; affects payback and tier design.", category: "modeling", glossary: ["activation", "time-to-value"] },
  { slug: "usage-forecast", title: "Usage Forecast", description: "Projected customer usage over time; used to design tiers and commitments.", category: "modeling", glossary: ["p50", "p90"] },
];
